### ISSUE TITLE
Add a check for Null Signature

### ISSUE THREAD

**Issue by rdubois-crypto** [ququzone/smart-accounts#5]
Currently the code is not checking the fact that r and s parts of the signature must differ from 0.

As a consequence (0,0) is accepted as valid for any pair (message, PublicKey)

This PR corrects the issue:
https://github.com/ququzone/smart-accounts/pull/4

**Comment by ququzone** [comment]
> Currently the code is not checking the fact that r and s parts of the signature must differ from 0.
> 
> As a consequence (0,0) is accepted as valid for any pair (message, PublicKey)
> 
> This PR corrects the issue: #4

Many thanks, merged.
